version: '3.4'
services:
  redis:
    image: "redis/redis-stack:latest"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--appendonly yes --aof-use-rdb-preamble yes"
volumes:
  redis_data: