version: '3.4'
services:
  postgres:
    image: 'postgres:15.4'
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=risk-server
volumes:
  redis_data: