version: '3.4'
services:
  postgres:
    image: 'postgres:15.4'
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=risk-server
    env_file:
      - .env
      